name: Utils
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/worker-utils run lint
      - run: pnpm -r --filter @web3-storage/worker-utils run test
  publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/worker-utils exec tsc
      - run: pnpm -r --filter @web3-storage/worker-utils publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
